inherit_from: .rubocop_todo.yml
AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - Gemfile
    - node_modules/**/*
    - db/schema.rb
    - lib/**/*.rake
    - config/environments/*.rb
