inherit_from: .rubocop_todo.yml
AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - Gemfile
    - node_modules/**/*
    - db/schema.rb
    - db/migrate/*.rb
    - lib/**/*.rake
    - config/environments/*.rb
    - config/initializers/*.rb
Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
