# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 90681e69000ef839ae19491ca6894e41db199d961775c9feb29f94f2c4c023d2e35ec7b3e134faee0ac3ba3490fd6a711ee9fe33112fa540982a6329b2ec8d69

test:
  secret_key_base: 49a4beb9093c6a4dc40e8a7bc6c218843088afff73fd5004cc3f493c601a3aefb54ed896dbd62d80406c7240a82f851a53a5785cf6fb619b78f15d48b608298b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
